"""EEC team roster used for championship calculations."""

TEAM_DRIVERS: dict[str, list[str]] = {
    "Warriors of Light": [
        "Celestia Astraethi",
        "Iryq",
        "Jadato",
        "Liokki",
        "Pele",
        "Luna",
    ],
    "7th Dawn Motorsports": [
        "Alphinaud",
        "Alisaie",
        "Estinein",
        "G'raha",
        "Minfilia",
        "Tataru",
    ],
    "Circle of Racing": [
        "Moenbryda",
        "Urianger",
        "Y'shtola",
        "Thancred",
        "Lyse",
        "Papalymo",
    ],
    "Manderville": [
        "Hildibrand Manderville",
        "Nashu Mhakaracca",
        "Greg",
        "Enkidu",
        "Godbert Manderville",
        "Julyan Manderville",
    ],
    "Blue Wing Racing": [
        "Emet-Selch",
        "Hythlodaeus",
        "Venat",
        "Elidibus",
        "Meteion",
        "Hermes",
    ],
    "Final Laps": [
        "Livingway",
        "Puddingway",
        "Ameliance",
        "Fourchenault",
        "Watcher",
        "Matoya",
    ],
    "Dawntrack": [
        "Krile",
        "Erenville",
        "Wuk Lamat",
        "Sphene",
        "Bakool Ja Ja",
        "Koana",
    ],
    "Warriors of Darkness": [
        "Ardbert",
        "Cylva",
        "Renda-Rae",
        "Lamitt",
        "Branden",
        "Nyelbert",
    ],
    "Steppe Sport": [
        "Sadu Dotharl",
        "Magnai Oronir",
        "Gosetsu",
        "Hien",
        "Cirina Mol",
        "Yugiri",
    ],
    "Scuderia Shadow": [
        "Gaius",
        "Zenos",
        "Ryne",
        "Gaia",
        "Feo Ul",
    ],
}

__all__ = ["TEAM_DRIVERS"]
